import type { ReactNode } from 'react'
import type { Metadata } from 'next'

import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { Rubik_Doodle_Shadow, DM_Sans, Montserrat } from 'next/font/google'
import { seedCategories } from '@/server/seed/category'

import Header from '@/components/client/header'
import { Toaster } from '@/components/admin/ui/toaster'
import Footer from '@/components/client/footer/footer'

import '../globals.css'

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700', '800'],
})

const rubikDoodleShadow = Rubik_Doodle_Shadow({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik-doodle-shadow',
  weight: ['400'],
})

const DMSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-sans',
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Slice Drys',
  description: 'Generated by create next app',
}

export default async function LocaleLayout(props: {
  children: ReactNode
  params: Promise<{ locale: LanguageType }>
}) {
  const url = process.env.NEXT_URL
  const params = await props.params

  const { locale } = params
  const { children } = props

  const messages = await getMessages()

  const categoriesData = await fetch(`${url}/api/categories`, {
    next: { revalidate: 60 },
  }).then((res) => res.json())

  if (process.env.NODE_ENV === 'development') {
    await seedCategories()
  }

  return (
    <html
      lang={locale}
      className={`${montserrat.variable} ${rubikDoodleShadow.variable} ${DMSans.variable}`}
    >
      <NextIntlClientProvider messages={messages}>
        <body className="flex min-h-svh flex-col">
          <Header productLinks={categoriesData.data} />
          <main className="flex-1">{children}</main>
          <Footer productLinks={categoriesData.data} />
          <Toaster />
        </body>
      </NextIntlClientProvider>
    </html>
  )
}
